### PR TITLE
fix issue adop-sonar#11

### PR DESCRIPTION
**Pull request by m4m51m**
Fix for #25

### CODE REVIEW

**Comment by svscorp** [comment]
@nickdgriffin @anton-kasperovich @SachinKSingh28 

Hi team, we validated this fix partially - line 71 `location ^~ /sonar {` does make sonar work. Though, changes on lines 45..72 are being checked by @mlushpenko

@m4m51m can you please comment why 45..72 are present in the fix? Also, can you please split the PR to two, one for SonarQube actual fix another for 45..72? I believe we can merge it faster if looks good for the team.

Thank you.

**Comment by svscorp** [comment]
Ok, we checked second part of the PR and status page is not working (at least on existing stable platform), maybe if @m4m51m can comment what 45..72 is there for it will be more clear.

@m4m51m can you pls split the "fix" in two PRs?

**Comment by mlushpenko** [comment]
@m4m51m  My bad, it is working - it fixes status page
image

**Comment by SachinKSingh28** [comment]
I have tested this changes and issue is fixed.

Steps below -

* Created a new image from feature/fix_issues_11_sonar branch on m4m51m/adop-nginx
* Updated docker compose file from adop-docker-compose repository with new tag for adop-nginx image used adop-sonar image 0.3.4
* Launched ADOP stack.

**Comment by svscorp** [comment]
Thanks, @SachinKSingh28

**Pull request merged**
